### ISSUE TITLE
README that explains how to use this

### ISSUE THREAD

**Issue by jamesdh** [foiseworth/flow-json-to-checkstyle-xml#2]
Would be great to have a simple tutorial in the readme to make it quicker/easier for users to get up and running with this. npmjs.com simply forwards to the readme here, which has nothing. 

Also, thanks for making this!

**Comment by foiseworth** [comment]
I'll have a look at this over the weekend - thanks for the push, I hadn't realised I'd left it in such a poor state 😄

**Comment by foiseworth** [comment]
Apologies for the delay. I've added a readme - feel free to add anything I've missed, it's been a while since I used this.
