### ISSUE TITLE
New release to NPM

### ISSUE THREAD

**Issue by jamesdh** [foiseworth/flow-json-to-checkstyle-xml#3]
The current version out on NPM is pre-error severity fix. That means the severity is reported as "undefined" which means the Jenkins checkstyle publisher doesn't know what to do with the reported errors.

**Comment by foiseworth** [comment]
Hi @jamesdh,
Apologies - I have now published the new version as requested. If you have any issues let me know.

**Comment by jamesdh** [comment]
Thank you! 👍
